apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cloudforge.fullname" . }}-config
  labels:
    {{- include "cloudforge.labels" . | nindent 4 }}
data:
  NODE_ENV: {{ .Values.backend.env.nodeEnv | quote }}
  PORT: {{ .Values.backend.env.port | quote }}
  DB_HOST: {{ .Values.backend.env.dbHost | quote }}
  DB_PORT: {{ .Values.backend.env.dbPort | quote }}
  DB_NAME: {{ .Values.backend.env.dbName | quote }}
  CORS_ORIGIN: {{ .Values.backend.env.corsOrigin | quote }}
