apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cloudforge.fullname" . }}-frontend
  labels:
    {{- include "cloudforge.labels" . | nindent 4 }}
    component: frontend
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      {{- include "cloudforge.frontend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "cloudforge.frontend.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.frontend.service.targetPort }}
              protocol: TCP
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
