apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudforge-prod
  namespace: argocd
  labels:
    env: production
    app: cloudforge
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: cloudforge-project
  source:
    repoURL: 'https://github.com/vikranth18devops/cloudforge_application.git'
    targetRevision: HEAD
    path: infra/helm
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: cloudforge-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
